export { default as NavBarComponent} from './navbarComponent'
export { default as CarouselComponent} from './carouselComponent'
export { default as CardComponent} from './cardComponent'
export { default as HomeComponent } from './homeComponent'
export { default as TableAppoimentComponent } from './tableAppoimentComponent'